# Generated by Django 6.0.1 on 2026-01-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idle_video', models.URLField(help_text='URL to Cloudinary idle video')),
                ('talking_video', models.URLField(help_text='URL to Cloudinary talking video')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
