# Generated by Django 6.0.1 on 2026-01-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='source_type',
            field=models.CharField(choices=[('text', 'Text Chat'), ('voice', 'Voice Chat')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='transcript',
            field=models.TextField(blank=True, help_text='Voice transcription (user speech-to-text)'),
        ),
    ]
