# Generated by Django 6.0.1 on 2026-01-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_source_type_chatmessage_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='corrected_text',
            field=models.TextField(blank=True, help_text='Corrected version of user input', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='explanation',
            field=models.TextField(blank=True, help_text='Grammar explanation in Ukrainian', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='translation',
            field=models.TextField(blank=True, help_text='Ukrainian translation of AI response', null=True),
        ),
    ]
