# Generated by Django 6.0.1 on 2026-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_corrected_text_chatmessage_explanation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='full_english_version',
            field=models.TextField(blank=True, help_text='Full phrase in English (for mixed language input)', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='has_errors',
            field=models.BooleanField(default=False, help_text='Indicates if message contains errors that need correction'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='transcript',
            field=models.TextField(blank=True, help_text='Voice transcription or phase metadata (initial/detailed_explanation/practice)'),
        ),
    ]
