# Generated by Django 6.0.1 on 2026-02-03 15:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_memory_options_memory_error_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pronunciationattempt',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pronunciationattempt',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='pronunciationattempt',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pronunciationattempt',
            name='topic',
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва квізу')),
                ('description', models.TextField(blank=True, verbose_name='Опис квізу')),
                ('passing_score', models.FloatField(default=6.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Прохідний бал (0-10)')),
                ('time_limit_minutes', models.IntegerField(blank=True, help_text='Ліміт часу в хвилинах (null = без ліміту)', null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('order', models.IntegerField(default=0, help_text='Порядок відображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='chat.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Квіз',
                'verbose_name_plural': 'Квізи',
                'ordering': ['lesson', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Множинний вибір'), ('true_false', 'Правда/Неправда'), ('fill_blank', 'Заповнити пропуск'), ('matching', 'Співставлення')], max_length=20, verbose_name='Тип питання')),
                ('question_text', models.TextField(verbose_name='Текст питання')),
                ('options', models.JSONField(default=dict, help_text='Варіанти відповідей (JSON). Формат залежить від типу питання')),
                ('correct_answer', models.JSONField(help_text='Правильна відповідь (JSON). Формат залежить від типу питання')),
                ('points', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Бали за питання')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснення правильної відповіді')),
                ('order', models.IntegerField(default=0, help_text='Порядок питання в квізі')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='chat.quiz', verbose_name='Квіз')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Оцінка (0-10)')),
                ('passed', models.BooleanField(default=False, verbose_name='Здано')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Початок')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершення')),
                ('time_spent_seconds', models.IntegerField(default=0, verbose_name='Витрачено часу (сек)')),
                ('answers', models.JSONField(default=dict, help_text='Всі відповіді користувача (JSON)')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='chat.quiz', verbose_name='Квіз')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Спроба квізу',
                'verbose_name_plural': 'Спроби квізів',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.JSONField(help_text='Відповідь користувача (JSON)')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('points_earned', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Зароблено балів')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='chat.question', verbose_name='Питання')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='chat.quizattempt', verbose_name='Спроба')),
            ],
            options={
                'verbose_name': 'Відповідь на питання',
                'verbose_name_plural': 'Відповіді на питання',
                'ordering': ['question__order'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
