# Generated by Django 6.0.1 on 2026-02-03 15:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_add_quiz_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(verbose_name='Текст домашнього завдання')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='URLs до файлів/зображень (якщо є)')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Подано')),
                ('attempt_number', models.IntegerField(default=1, verbose_name='Номер спроби')),
                ('status', models.CharField(choices=[('pending', 'Очікує оцінювання'), ('evaluated', 'Оцінено'), ('revised', 'Переглянуто/Виправлено')], default='pending', max_length=20, verbose_name='Статус')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='chat.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Подання домашнього завдання',
                'verbose_name_plural': 'Подання домашніх завдань',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Оцінка (0-10)')),
                ('criteria_scores', models.JSONField(default=dict, help_text='Оцінки по критеріям (JSON)')),
                ('feedback_text', models.TextField(verbose_name='Фідбек (загальний)')),
                ('errors', models.JSONField(default=list, help_text='Список помилок з поясненнями (JSON)')),
                ('strengths', models.JSONField(default=list, help_text='Сильні сторони (JSON list)')),
                ('improvements', models.JSONField(default=list, help_text='Рекомендації для покращення (JSON list)')),
                ('next_step', models.TextField(blank=True, verbose_name='Наступний крок у навчанні')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True, verbose_name='Оцінено')),
                ('evaluator_type', models.CharField(choices=[('ai', 'AI (Gemini)'), ('teacher', 'Вчитель')], default='ai', max_length=10, verbose_name='Тип оцінювача')),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='chat.homeworksubmission', verbose_name='Подання')),
            ],
            options={
                'verbose_name': 'Фідбек по домашньому завданню',
                'verbose_name_plural': 'Фідбеки по домашнім завданням',
            },
        ),
    ]
