# Generated by Django 6.0.1 on 2026-02-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_add_homework_submission_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='roleplaysession',
            name='messages_history',
            field=models.JSONField(default=list, help_text="JSON: [{'role': 'user'/'model', 'content': 'текст'}] - формат для Gemini API"),
        ),
        migrations.AddField(
            model_name='roleplaysession',
            name='system_prompt',
            field=models.TextField(blank=True, help_text='System prompt для Gemini API (зберігається для відновлення контексту)'),
        ),
    ]
