# Generated by Django 6.0.1 on 2026-02-03 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_update_roleplay_session_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True, verbose_name='Слово')),
                ('translation_uk', models.CharField(max_length=255, verbose_name='Переклад українською')),
                ('definition_en', models.TextField(verbose_name='Визначення англійською')),
                ('example_sentence', models.TextField(blank=True, verbose_name='Приклад речення')),
                ('word_type', models.CharField(choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('preposition', 'Preposition'), ('conjunction', 'Conjunction'), ('pronoun', 'Pronoun'), ('interjection', 'Interjection'), ('phrase', 'Phrase')], default='noun', max_length=20, verbose_name='Частина мови')),
                ('difficulty_level', models.CharField(choices=[('A0', 'A0 - Starter'), ('A1', 'A1 - Beginner'), ('A2', 'A2 - Elementary'), ('B1', 'B1 - Intermediate'), ('B2', 'B2 - Upper Intermediate'), ('C1', 'C1 - Advanced'), ('C2', 'C2 - Proficient')], default='A1', max_length=2, verbose_name='Рівень складності')),
                ('frequency_rank', models.IntegerField(blank=True, help_text='Частота використання (1 = найпопулярніше)', null=True)),
                ('audio_url', models.URLField(blank=True, null=True, verbose_name='URL аудіо вимови')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL зображення')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Словникове слово',
                'verbose_name_plural': 'Словникові слова',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='UserVocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Нове'), ('learning', 'Вивчається'), ('learned', 'Вивчено'), ('mastered', 'Засвоєно'), ('forgotten', 'Забуто')], default='new', max_length=20, verbose_name='Статус')),
                ('times_seen', models.IntegerField(default=0, verbose_name='Скільки разів зустрічалося')),
                ('times_correct', models.IntegerField(default=0, verbose_name='Скільки разів правильно використано')),
                ('times_incorrect', models.IntegerField(default=0, verbose_name='Скільки разів неправильно')),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Останній перегляд')),
                ('next_review_at', models.DateTimeField(blank=True, null=True, verbose_name='Наступний перегляд')),
                ('ease_factor', models.FloatField(default=2.5, help_text='Ease Factor для SM-2 алгоритму')),
                ('interval_days', models.IntegerField(default=1, help_text='Інтервал повторення в днях')),
                ('repetitions', models.IntegerField(default=0, help_text='Кількість успішних повторень підряд')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learned_from_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabulary_learned', to='chat.lesson', verbose_name='Вивчено з уроку')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_progress', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='chat.vocabularyword', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Прогрес по словнику',
                'verbose_name_plural': 'Прогрес по словнику',
                'ordering': ['next_review_at'],
                'unique_together': {('user', 'word')},
            },
        ),
        migrations.CreateModel(
            name='LessonVocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=True, help_text='Основне слово уроку чи додаткове')),
                ('context', models.TextField(blank=True, verbose_name='Контекст використання в уроці')),
                ('order', models.IntegerField(default=0, help_text='Порядок в списку')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_items', to='chat.lesson', verbose_name='Урок')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_usages', to='chat.vocabularyword', verbose_name='Слово')),
            ],
            options={
                'verbose_name': 'Словник уроку',
                'verbose_name_plural': 'Словники уроків',
                'ordering': ['lesson', 'order'],
                'unique_together': {('lesson', 'word')},
            },
        ),
    ]
