# Generated by Django 6.0.1 on 2026-02-03 15:56

import apps.chat.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_add_vocabulary_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='homework_instructions',
            field=models.JSONField(blank=True, default=dict, help_text='Критерії оцінювання домашнього завдання', validators=[apps.chat.validators.validate_homework_instructions], verbose_name='Інструкції для AI перевірки'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='role_play_scenario',
            field=models.JSONField(blank=True, default=dict, help_text="JSON: {'setting': 'опис місця', 'ai_role': 'роль AI', 'user_role': 'роль користувача', 'objectives': [], 'difficulty': 'easy/medium/hard'}", validators=[apps.chat.validators.validate_role_play_scenario], verbose_name='Сценарій рольової гри'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='voice_practice_prompts',
            field=models.JSONField(blank=True, default=list, help_text='Список промптів для генерації AI діалогу', validators=[apps.chat.validators.validate_voice_practice_prompts], verbose_name='Промпти для AI'),
        ),
    ]
