# Generated by Django 6.0.1 on 2026-02-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_add_kb_level_and_module_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='is_universal',
            field=models.BooleanField(default=False, help_text='Чи доступний для всіх рівнів'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='level',
            field=models.CharField(choices=[('A0', 'Starter'), ('A1', 'Elementary'), ('A2', 'Pre-Intermediate'), ('B1', 'Intermediate'), ('B2', 'Upper-Intermediate'), ('C1', 'Advanced'), ('C2', 'Proficiency')], default='A1', help_text='Рівень складності контенту', max_length=2),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='Модулі, до яких належить цей контент', related_name='knowledge_items', to='chat.module'),
        ),
    ]
