# Generated by Django 6.0.1 on 2026-02-03 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_update_kb_with_level_and_modules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_uk', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_uk', models.TextField()),
                ('icon', models.CharField(help_text='Emoji або URL', max_length=50)),
                ('points', models.IntegerField(default=10, help_text='Бали за досягнення')),
                ('category', models.CharField(choices=[('progress', 'Progress'), ('streak', 'Streak'), ('mastery', 'Mastery'), ('social', 'Social')], max_length=20)),
                ('tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=20)),
                ('requirements', models.JSONField(help_text='Умови для отримання')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Досягнення',
                'verbose_name_plural': 'Досягнення',
                'ordering': ['category', 'tier'],
            },
        ),
        migrations.CreateModel(
            name='LearningStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_activity_date', models.DateField(auto_now=True)),
                ('total_active_days', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Стрік навчання',
                'verbose_name_plural': 'Стріки навчання',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('lesson_difficulty', 'Складність уроку'), ('ai_quality', 'Якість AI'), ('bug_report', 'Звіт про помилку'), ('suggestion', 'Пропозиція')], max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], default='neutral', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_reviewed', models.BooleanField(default=False)),
                ('admin_response', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Відгук користувача',
                'verbose_name_plural': 'Відгуки користувачів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lessons_completed', models.IntegerField(default=0)),
                ('time_spent_minutes', models.IntegerField(default=0)),
                ('homework_submitted', models.IntegerField(default=0)),
                ('roleplay_sessions', models.IntegerField(default=0)),
                ('voice_practice_sessions', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Денна активність',
                'verbose_name_plural': 'Денна активність',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('progress', models.FloatField(default=100.0, help_text='Прогрес для прогресивних досягнень (0-100)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_notified', models.BooleanField(default=False)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Досягнення користувача',
                'verbose_name_plural': 'Досягнення користувачів',
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
