# Generated by Django 6.0.1 on 2026-02-03 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_add_achievements_and_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='quiz_score',
            field=models.FloatField(blank=True, help_text='Оцінка за тест (0-10)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
